---
- hosts: all
  become: true
  tasks:

  - name: Install apache2 and PHP packages
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: true